### ISSUE TITLE
Cannot download anything.

### ISSUE THREAD

**Issue by trikyas** [nishad/udemy-dl-windows#106]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

The error I get is this.

Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 609, in get_data
    get_video(link, filename)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 570, in get_video
    check_downloaded(link, filename, downloader, tmp_file=tmp_file)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 582, in check_downloaded
    download_status = download(link, tmp_file, update_progress, downloader_name)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/download.py", line 38, in download
    aria2c_dl(link, filename)
  File "/usr/local/lib/python2.7/site-packages/udemy_dl/download.py", line 86, in aria2c_dl
    subprocess.call(command)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 972, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
