### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NeiL978** [nishad/udemy-dl-windows#113]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : udemy-dl.exe 2.1.2.

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}

when I downloading the course sometime will get this error. 

10/12 03:01:06 [NOTICE] Download GID#867b6a5214a3b9ab not complete: D:/course/01-introduction-getting-started/654321-004-how-to-ask-great-questions.mp4.part23.tmp

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
867b6a|ERR |       0B/s|D:/course/01-introduction-getting-started/654321-004-how-to-ask-great-questions.mp4.part23.tmp

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
Error in sys.excepthook:
Traceback (most recent call last):
  File "<string>", line 55, in logging_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa8 in position 24: ordinal not in range(128)

Original exception was:
Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 648, in get_data
  File "<string>", line 601, in get_video
  File "<string>", line 623, in check_downloaded
WindowsError: [Error 2] 系統找不到指定的檔案。
udemy_dl returned -1

**Comment by NeiL978** [comment]
delete aria2c just work perfect.
