### ISSUE TITLE
[BUG] File name too long for destination folder

### ISSUE THREAD

**Issue by Zone22** [nishad/udemy-dl-windows#115]
Version : **udemy-dl 2.1.2**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---
In summary udemy-dl failed to download the project due a Windows error stating that the one of file names is too long. Then udemy-dl expected to file that didn't exist thus the ERROR-1198.

The issue can be repeatedly duplicated with the following course.
https://www.udemy.com/photography-masterclass-your-complete-guide-to-photography

I first noted this issue when trying to download the course.

```
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 663, in get_data
  File "<string>", line 562, in get_attached_file
  File "<string>", line 623, in check_downloaded
WindowsError: [Error 3] The system cannot find the path specified
None
```

This suggests that the file that should've been downloaded was not in fact downloaded, specifically  "D:/Backup/Library/Desktop/udemy-dl-win/photography-masterclass-your-complete-guide-to-photography/01 Introduction to the Course/./attached_files/004 DOWNLOAD A Comprehensive Beginners Guide to Photography/Learn-Photography-A-Comprehensive-Beginners-Guide.pdf.tmp"

As a temporary workaround I downloaded "Learn-Photography-A-Comprehensive-Beginners-Guide.pdf" then renamed it "Learn-Photography-A-Comprehensive-Beginners-Guide.pdf.tmp" and tried to place it into .../004 DOWNLOAD A Comprehensive Beginners Guide to Photography/ folder. with the hopes of rerunning the program and bypassing the issue without really looking into it.

This led to the below error
![capture](https://cloud.githubusercontent.com/assets/1348848/19332899/13be9366-90b6-11e6-8bd5-5844ccd2a806.PNG)

**Comment by hungdev** [comment]
How can i fix? pls give me the solution.

**Comment by whench18** [comment]
Hi, if there's any problem with a path too long Issue, I suggest to try Long Path Tool. It will surely help you with your problem.

**Comment by Dimensional** [comment]
I still get this error. Sadly I can't avoid long or short names, because most of the courses I'm downloading use extremely long names for every lecture. Each chapter is on average 80 characters long, and that's not counting the lecture names or attachments.
