### ISSUE TITLE
[BUG] Unicode Encoder Error : Character maps to <undefinied> when downloading attached files.

### ISSUE THREAD

**Issue by descite** [nishad/udemy-dl-windows#117]
Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **2.1.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [ x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked that the issue I'm posting isn't already reported.
- [x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [x ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Got error:
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 628, in get_data
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
  File "encodings\cp775.py", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\xe7' in position 27: character maps to <undefined>
None
udemy_dl returned -1

when downloading from url https://www.udemy.com/experience-design-patterns/
Tried multiple times, got same error.
Seems that 'charmap' codec misses http://www.fileformat.info/info/unicode/char/00E7/index.htm

**Comment by thanossv** [comment]
I get a very similar error when downloading from: https://www.udemy.com/japanese-n5-course

```
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 628, in get_data
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
  File "encodings\cp737.py", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 25-28: character maps to <undefined>
None
udemy_dl returned -1
```

I am using Python 3.6.0, and the tool successfully downloaded all the previous files. 
The first file that couldn't be downloaded using Japanese characters, so it seems that they aren't encoded as they should.

**Comment by aifuenzalida** [comment]
I get a very similar error when downloading from: https://www.udemy.com/read-japanese-fast/

Downloading Audio: 034 Lesson 9 - Potential Form

 034 Lesson 9 - Potential Form.mp3 already exists
 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 825, in udemy_dl
  File "udemy_dl.py", line 680, in get_data
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
  File "encodings\cp850.py", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\u3066' in position 37: character maps to <undefined>
Failed to execute script udemy_dl

The file is this: Lesson 10 - て Form
