### ISSUE TITLE
[BUG]UnicodeEncodeError: 'ascii' codec can't encode characters in position 380-384: ordinal not in range(128) None

### ISSUE THREAD

**Issue by mouad1234** [nishad/udemy-dl-windows#119]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : 2.1.2

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 648, in get_data
  File "<string>", line 607, in get_video
  File "<string>", line 621, in check_downloaded
  File "download.py", line 30, in download
  File "download.py", line 80, in aria2c_dl
  File "subprocess.py", line 522, in call
  File "subprocess.py", line 710, in __init__
  File "subprocess.py", line 958, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 380-384: ordinal not in range(128)
None
udemy_dl returned -1
when downloading from url https://www.udemy.com/unity-course-in-arabic/

**Comment by stalker83** [comment]
i have the same error. is there no way to use UTF-8 encoding?
Regards

**Comment by X4V1** [comment]
Same for me. I try to download the course Spring and Hibernate in English.
It fails everytime at the same time.
It's the same with aria2c or curl.

`
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 663, in get_data
  File "<string>", line 562, in get_attached_file
  File "<string>", line 621, in check_downloaded
  File "download.py", line 46, in download
  File "download.py", line 112, in requests_dl
IOError: [Errno 2] No such file or directory: u'.\\attached_files\\077 Practice Activity 6 - Bean Scopes with Annotations\\06-practice-activity-bean-scopes-annotations.pdf.tmp'
None
udemy_dl returned -1
`

**Comment by YHOYO** [comment]
Downloading Video: 001 Introducción

[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 648, in get_data
  File "<string>", line 607, in get_video
  File "<string>", line 621, in check_downloaded
  File "download.py", line 30, in download
  File "download.py", line 80, in aria2c_dl
  File "subprocess.py", line 522, in call
  File "subprocess.py", line 710, in __init__
  File "subprocess.py", line 958, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 349: ordinal not in range(128)
None
udemy_dl returned -1

**Comment by YHOYO** [comment]
use `--safe-file-names ` in order to get a  successfully downloaded   .. check [https://github.com/nishad/udemy-dl/issues/171](url)

**Comment by hungdev** [comment]
Thank @YHOYO .
