### ISSUE TITLE
[BUG] udemy-dl-win-2.1.2 - errors out if there are too many parts of a video file.

### ISSUE THREAD

**Issue by darshanlbangre** [nishad/udemy-dl-windows#121]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : 2.1.2

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [ x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked that the issue I'm posting isn't already reported.
- [x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [ x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}
Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.

I end up with below error after downloading like some 30 or 40 files (parts, lessons). I will have to start the download again which will resume from previous part but again error out after downloading some files.

If there are any errors, then see the log file. See '-l' option in help/man page for details.
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 648, in get_data
  File "<string>", line 601, in get_video
  File "<string>", line 623, in check_downloaded
WindowsError: [Error 2] The system cannot find the file specified
None
udemy_dl returned -1

**Comment by JustasPolis** [comment]
Experiencing same error.

**Comment by m0rpheux** [comment]
same here but the creator isn't responding the issues :(

**Comment by darshanlbangre** [comment]
Used --external-downloader curl as a workaround and infact the download was much quicker.

**Comment by m0rpheux** [comment]
thanks @darshanlbangre  seems to be working with that argument 👍

**Comment by isitmeor** [comment]
where did you put the --external-downloader curl  command?
can you five an example

tia

**Comment by m0rpheux** [comment]
@isitmeor  before the url you can either write --external-downloader curl or write -d curl

**Comment by m0rpheux** [comment]
it's kinda working still got like 2 courses who threw the error

**Comment by isitmeor** [comment]
this might be to much to ask but... is it possible to save them as MKV files?

**Comment by m0rpheux** [comment]
@isitmeor based on the arguments i don't think so plus i think they come only like mp4 from udemy i think you would have to user another software to convert it to MKV

**Comment by hungdev** [comment]
Thank @darshanlbangre . Its work for me.

**Comment by moein147** [comment]
Hi. please dear nishad please create a video and show us how can i download course from udemy. because udemy change system and this method is not good because show me error.
please see this video. this video show you that this methos is not working and i sugest that create another video. 
https://www.youtube.com/watch?v=XeiJW2HRUKk
