### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by samehfrehat** [nishad/udemy-dl-windows#124]
/
[INFO-835] Downloading to: C:\python45\scripts\complete-guide-to-build-iot-things-from-scratch-to-market

[INFO-107] Trying to log in ...
[INFO-137] Login success.
[INFO-169] Found course id: 709804
Traceback (most recent call last):
  File "udemy-dl", line 7, in <module>
    main()
  File "C:\Python45\lib\site-packages\udemy_dl\udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "C:\Python45\lib\site-packages\udemy_dl\udemy_dl.py", line 666, in udemy_dl
    for data in get_data_links(course_id, lecture_start, lecture_end):
  File "C:\Python45\lib\site-packages\udemy_dl\udemy_dl.py", line 359, in get_data_links
    course_data_len = len(course_data['results'])
KeyError: 'results'

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
