### ISSUE TITLE
it not works with ö ä etc.

### ISSUE THREAD

**Issue by atilladeniz** [nishad/udemy-dl-windows#125]
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 648, in get_data
  File "<string>", line 607, in get_video
  File "<string>", line 621, in check_downloaded
  File "download.py", line 30, in download
  File "download.py", line 80, in aria2c_dl
  File "subprocess.py", line 522, in call
  File "subprocess.py", line 710, in __init__
  File "subprocess.py", line 958, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 343: ordinal not in range(128)

**Comment by ValeriySh** [comment]
--safe-file-names ?

**Comment by veDev** [comment]
# Thanks
Can confirm that it works with the addition of <b>"--safe-file-names"</b>

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
