### ISSUE TITLE
[BUG] [ERROR-1198] and [Error 206]

### ISSUE THREAD

**Issue by downraver** [nishad/udemy-dl-windows#134]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **2.1.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [x ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked that the issue I'm posting isn't already reported.
- [x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [x
![error](https://cloud.githubusercontent.com/assets/10491629/23826055/4aeca40e-0663-11e7-99d5-e2ae61dcce4d.jpg)
 ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{Hello guys. I have been using this app for about a week now and I love it. Thanks devs. I have been getting errors when trying to download specific videos. For this specific case, the error reads name too long. Please see attached picture. Thanks!}

**Comment by SauROnmiKE** [comment]
Greetings from me as well.
I have the [ERROR-1198] error as well.

`[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 705, in udemy_dl
  File "<string>", line 382, in get_data_links
KeyError: u'results'
None
udemy_dl returned -1`

I did not yet find any answer yet and the creator doesn't seem to be active.

**Comment by LuisEGR** [comment]
It looks like is your folder location problem, try to dowload directly to C: , also you could try to add this parameters: --use-ffmpeg --external-downloader curl --safe-file-names

**Comment by diridou** [comment]
Hi SauROnmiKE , 
I have the same problem, did you find a solution ?
