### ISSUE TITLE
I am unable to download a course due to this error (snapshot)

### ISSUE THREAD

**Issue by Mannugithub** [nishad/udemy-dl-windows#137]
I am unable to download a course due to this error 

[INFO-157] Login success.
[INFO-189] Found course id: 979026
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 705, in udemy_dl
  File "<string>", line 382, in get_data_links
KeyError: u'results'
None
udemy_dl returned -1

**Comment by schatterjee4** [comment]
me too

**Comment by Jhony33** [comment]
Me too :(

**Comment by yolao** [comment]
Me too :(
