### ISSUE TITLE
[BUG] [ERROR-56] Can't download non-existing attachment

### ISSUE THREAD

**Issue by aolko** [nishad/udemy-dl-windows#147]
```
[ERROR-56] Traceback (most recent call last):
  File "udemy_dl.py", line 906, in <module>
  File "udemy_dl.py", line 903, in main
  File "udemy_dl.py", line 762, in udemy_dl
  File "udemy_dl.py", line 680, in get_data
  File "udemy_dl.py", line 579, in get_attached_file
  File "udemy_dl.py", line 638, in check_downloaded
  File "download.py", line 46, in download
  File "download.py", line 112, in requests_dl
IOError: [Errno 2] No such file or directory: u'.\\attached_files\\course-name\\file-name.zip.tmp'
```

The file does not exist in the course, instead of skepping it, udemy-dl tries to download it and fails

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
