### ISSUE TITLE
Does this still work

### ISSUE THREAD

**Issue by kenshinman** [nishad/udemy-dl-windows#148]
[QUESTION]
I am running it on windows10 and I want to know if it still works.

I got this error

    ```
     Traceback (most recent call last):
     File "logging\__init__.py", line 870, in emit
     File "site-packages\colorama\ansitowin32.py", line 40, in write
     File "site-packages\colorama\ansitowin32.py", line 141, in write
     File "site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
     File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
     LookupError: unknown encoding: cp65001
     Logged from file __init__.py, line 1198
     udemy_dl returned -1
    ```

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
