### ISSUE TITLE
Help me   udemy_dl returned -1

### ISSUE THREAD

**Issue by mbflores** [nishad/udemy-dl-windows#155]
I've been enrolled in that course btw.

[INFO-884] Downloading to: C:\Users\Bryan\Downloads\udemy-dl-win-2.1.2\udemy-dl-win\xamarin-forms-course

[INFO-127] Trying to log in ...
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 697, in udemy_dl
  File "<string>", line 129, in login
  File "<string>", line 115, in get_csrf_token
  File "<string>", line 85, in get
  File "site-packages\requests\sessions.py", line 480, in get
  File "site-packages\requests\sessions.py", line 468, in request
  File "site-packages\requests\sessions.py", line 576, in send
  File "site-packages\requests\adapters.py", line 447, in send
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
None
udemy_dl returned -1

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
