### ISSUE TITLE
[BUG] Exception AbstractCommand 403 Err 16, ErrNum 3

### ISSUE THREAD

**Issue by claws61821** [nishad/udemy-dl-windows#162]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **2.1.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

When downloading the course "The Disobedient Writer: Break the Rules and Free Your Story" the process breaks consistently on the attached files for lecture 031. I have checked the download PATH length and verified as best able that it does not exceed Windows' limits for such.

`Downloading attached files

07/25 12:40:04 [NOTICE] Downloading 1 item(s)

07/25 12:40:05 [ERROR] CUID#7 - Download aborted. URI=https://udemy-assets-on-de
mand.udemy.com/{snip}/original.pdf
?nva=20170725221007&filename=Complex-causality-handout.pdf&download=True&token={snip}
Exception: [AbstractCommand.cc:403] errorCode=16 URI=https://udemy-assets-on-dem
and.udemy.com/{snip}/original.pdf?
nva=20170725221007&filename=Complex-causality-handout.pdf&download=True&token={snip}
  -> [RequestGroup.cc:760] errorCode=16 Download aborted.
  -> [AbstractDiskWriter.cc:206] errNum=3 errorCode=16 Failed to open the file h
:/educational/udemy-dl/disobedient-writer/12 Unit 10 Levels and layers/./attache
d_files/031 The rule A causes B then B causes C .../Complex-causality-handout.pd
f.tmp, cause: The system cannot find the path specified.

07/25 12:40:05 [NOTICE] Download GID#{snip} not complete: h:/education
al/udemy-dl/disobedient-writer/12 Unit 10 Levels and layers/./attached_files/031
 The rule A causes B then B causes C .../Complex-causality-handout.pdf.tmp

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
1adbe8|ERR |       0B/s|h:/educational/udemy-dl/disobedient-writer/12 Unit 10 Le
vels and layers/./attached_files/031 The rule A causes B then B causes C .../Com
plex-causality-handout.pdf.tmp

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page
 for details.
 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 825, in udemy_dl
  File "udemy_dl.py", line 718, in get_data
  File "udemy_dl.py", line 612, in get_attached_file
  File "udemy_dl.py", line 675, in check_downloaded
WindowsError: [Error 3] The system cannot find the path specified
Failed to execute script udemy_dl`

**Comment by javaByte** [comment]
How to resolve this error???
Please Reply

**Comment by m0rpheux** [comment]
@javaByte  file path is too large manually download that pdf and the run the commands again with the argument --lecture-start  and --lecture-end and don't forget to put the number of the lecture after that pdf

**Comment by javaByte** [comment]
@m0rpheux  Thanks :)  It worked only for free course videos.
How can I download the Paid Course Videos for Free?

**Comment by osazemeu** [comment]
@javaByte downloader doesn't download Paid Course Videos for free. You need to have access to course to download it

**Comment by RISHITSONECHA** [comment]
is there anyway to download paid courses for free?
