### ISSUE TITLE
[BUG] Downloading fails due to script !?

### ISSUE THREAD

**Issue by mrHJS** [nishad/udemy-dl-windows#163]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [ X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I tried using the latest windows version. The download starts and works well for quite a few minutes and then all of a sudden, the download stops with the following error message:

 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 825, in udemy_dl
  File "udemy_dl.py", line 718, in get_data
  File "udemy_dl.py", line 593, in get_attached_file
  File "udemy_dl.py", line 113, in get
  File "site-packages\requests\sessions.py", line 515, in get
  File "site-packages\requests\sessions.py", line 502, in request
  File "site-packages\requests\sessions.py", line 612, in send
  File "site-packages\requests\adapters.py", line 490, in send
ConnectionError: ('Connection aborted.', error(10054, 'Eine vorhandene Verbindun
g wurde vom Remotehost geschlossen'))
Failed to execute script udemy_dl

The German "'Eine vorhandene Verbindung wurde vom Remotehost geschlossen'" would be something like - an existing connection was closed by the remote host - in English. Does that mean that udemy is stopping the connection?

**Comment by tofanelli** [comment]
Same error here....

> F:\Udemy\udemy2>udemy-dl -u xxxx -p yyyy https://
> www.udemy.com/curso-de-desenvolvimento-web-com-es6-typescript-e-angular-4
>  Downloading to: F:\Udemy\udemy2\curso-de-desenvolvimento-web-com-es6-typescript
> -e-angular-4
> 
>  Trying to log in ...
>  Login success.
>  Found course id: 1138310
>  Found course title: Curso de Desenvolvimento WEB com ES6, TypeScript e Angular
> 4
> Getting course data: 100.00% [====================] Done
> 
> 
> Downloading Video: 001 Mapa do curso
> 
> 
> 09/13 07:41:23 [NOTICE] Downloading 1 item(s)
> [#979ddf 9.9MiB/10MiB(98%) CN:2 DL:0.9MiB]
> 09/13 07:41:36 [NOTICE] Download complete: F:/Udemy/udemy2/curso-de-desenvolvime
> nto-web-com-es6-typescript-e-angular-4/01 Introdução/654321-001 Mapa do curso.mp
> 4.tmp
> 
> Download Results:
> gid   |stat|avg speed  |path/URI
> ======+====+===========+=======================================================
> 979ddf|OK  |   895KiB/s|F:/Udemy/udemy2/curso-de-desenvolvimento-web-com-es6-typ
> escript-e-angular-4/01 Introdução/654321-001 Mapa do curso.mp4.tmp
> 
> Status Legend:
> (OK):download completed.
>  Exception
> Traceback (most recent call last):
>   File "udemy_dl.py", line 976, in <module>
>   File "udemy_dl.py", line 971, in main
>   File "udemy_dl.py", line 825, in udemy_dl
>   File "udemy_dl.py", line 680, in get_data
>   File "site-packages\colorama\ansitowin32.py", line 40, in write
>   File "site-packages\colorama\ansitowin32.py", line 141, in write
>   File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
>   File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
>   File "encodings\cp437.py", line 12, in encode
> UnicodeEncodeError: 'charmap' codec can't encode character u'\xe3' in position 4
> 6: character maps to <undefined>
> Failed to execute script udemy_dl


I closed the prompt, restarted  the machine, using the latest Python version in a fresh windows install...
