### ISSUE TITLE
QUESTION  Failed to execute script udemy_dl    

### ISSUE THREAD

**Issue by javaByte** [nishad/udemy-dl-windows#164]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Downloading attached files

08/01 21:01:00 [NOTICE] Downloading 1 item(s)
[#e9840e 0B/0B CN:1 DL:0B]
08/01 21:01:04 [ERROR] CUID#7 - Download aborted. URI=https://udemy-assets-on-demand.udemy.com/2014-09-18_21-36-12-c2ea86c39b0b8e0cd8dc5ec5c0ea5e79/2014-09-18_21-36-12__DeltaBartalk-master.pdf?nva=20170801200100&filename=Delta-Bartalk-Master.pdf&download=True&token=079ee6e8353295bb4426c
Exception: [AbstractCommand.cc:403] errorCode=16 URI=https://udemy-assets-on-demand.udemy.com/2014-09-18_21-36-12-c2ea86c39b0b8e0cd8dc5ec5c0ea5e79/2014-09-18_21-36-12__DeltaBartalk-master.pdf?nva=20170801200100&filename=Delta-Bartalk-Master.pdf&download=True&token=079ee6e8353295bb4426c
  -> [RequestGroup.cc:760] errorCode=16 Download aborted.
  -> [AbstractDiskWriter.cc:206] errNum=3 errorCode=16 Failed to open the file C:/Users/Gaurav/Downloads/New folder/udemy-dl-windows-master/dist/become-an-android-developer-from-scratch/02 Computer Memory Think like your machine WEEK 1B/./attached_files/018 APP DEMO Bartalk and Android Studio Setup Instructions/Delta-Bartalk-Master.pdf.tmp, cause: The system cannot find the path specified.

08/01 21:01:04 [NOTICE] Download GID#e9840e97b0b2a6c3 not complete: C:/Users/Gaurav/Downloads/New folder/udemy-dl-windows-master/dist/become-an-android-developer-from-scratch/02 Computer Memory Think like your machine WEEK 1B/./attached_files/018 APP DEMO Bartalk and Android Studio Setup Instructions/Delta-Bartalk-Master.pdf.tmp

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
e9840e|ERR |       0B/s|C:/Users/Gaurav/Downloads/New folder/udemy-dl-windows-master/dist/become-an-android-developer-from-scratch/02 Computer Memory Think like your machine WEEK 1B/./attached_files/018 APP DEMO Bartalk and Android Studio Setup Instructions/Delta-Bartalk-Master.pdf.tmp

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 825, in udemy_dl
  File "udemy_dl.py", line 718, in get_data
  File "udemy_dl.py", line 612, in get_attached_file
  File "udemy_dl.py", line 675, in check_downloaded
WindowsError: [Error 3] The system cannot find the path specified
Failed to execute script udemy_dl

**Comment by rafaelmaruta** [comment]
here this error too

**Comment by RISHITSONECHA** [comment]
I got this error:-



 Downloading to: C:\Users\HP\Desktop\udemy-dl-windows\video-course-c-from-beginner-to-expert

 Trying to log in ...
 Login success.
 Found course id: 43718
 Found course title: C++: From Beginner to Expert
 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 785, in udemy_dl
  File "udemy_dl.py", line 431, in get_data_links
KeyError: u'results'
Failed to execute script udemy_dl
'kw' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Freepublic9** [comment]
Hi Nishad,
I am getting the similar error, please find below the error message for your kind help.
Trying to log in ...
 Login success.
 Found course id: 1188787 (I changed this here for anonymity)
 Found course title: abcxxxx123  (I changed this here for anonymity)
 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 785, in udemy_dl
  File "udemy_dl.py", line 431, in get_data_links
KeyError: u'results'
Failed to execute script udemy_dl

hoping to hear from you at your soonest.
cheers,
Free

**Comment by Leovalcante** [comment]
@javaByte  your error was already reported in issue #116 :  WindowsError: [Error 3] The system cannot find the path specified. 

This is the solution i found:
> I solved using the option --lecture-start NUMBER_OF_NEXT_LESSION.
I've checked the data after the full download and the data are all ok.

@RISHITSONECHA , @Freepublic9 your one is a different error.

Hope this helps 😸

Have a nice day,
Valerio

**Comment by poode** [comment]
I faced that error too because the course attachment sometimes not a file. It is a url for a another website
