### ISSUE TITLE
long file name bug

### ISSUE THREAD

**Issue by krzysztofautomatyk** [nishad/udemy-dl-windows#173]
sorry for my english 

When i want to download videocurs a with long name of title i have error:

```
 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 825, in udemy_dl
  File "udemy_dl.py", line 718, in get_data
  File "udemy_dl.py", line 588, in get_attached_file
  File "udemy_dl.py", line 553, in mkdir
  File "os.py", line 157, in makedirs
WindowsError: [Error 206] Nazwa pliku lub jej rozszerzenie są za długie: u'.\\attached_files\\016 Using table-stripped and table-bordered classes to styling you table body'
Failed to execute script udemy_dl

```

**Comment by tofanelli** [comment]
@krzysztofautomatyk .... i was struggling with this same error, but I remembered there is a " -o " option, where you can set the folder where the course will be downloaded, so, instead to leave the program set the folder, use this option, something like " -o 1", where this "1" is the name of the folder. After done, you can just rename the folder and green to go =D

**Comment by Vagonn** [comment]
@tofanelli Can you post "an example in cmd" please?
