### ISSUE TITLE
BUG: Udemy Script Error 

### ISSUE THREAD

**Issue by richard2092** [nishad/udemy-dl-windows#178]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **2.1.3**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [ X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [ X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [X ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

The error is as follows:

Downloading attached files

10/20 11:55:30 [NOTICE] Downloading 1 item(s)

10/20 11:55:31 [ERROR] CUID#7 - Download aborted. URI=https://udemy-assets-on-demand.udemy.com/2016-10-08_17-17-05-12afaf8ace0f0fedf9701587b2c87a2e/original.xlsm?nva=20171020202530&download=True&filename=9.Interest-expenses-Extraordinary-items-and-Taxes-Solved.xlsm&token=06509c9bca2ed19ab43ce
Exception: [AbstractCommand.cc:403] errorCode=16 URI=https://udemy-assets-on-demand.udemy.com/2016-10-08_17-17-05-12afaf8ace0f0fedf9701587b2c87a2e/original.xlsm?nva=20171020202530&download=True&filename=9.Interest-expenses-Extraordinary-items-and-Taxes-Solved.xlsm&token=06509c9bca2ed19ab43ce
  -> [RequestGroup.cc:760] errorCode=16 Download aborted.
  -> [AbstractDiskWriter.cc:206] errNum=3 errorCode=16 Failed to open the file C:/Users/Richard/Documents/udemy-dl-windows/the-complete-investment-banking-course-2016/13 DCF Valuation - Forecasting of key PL items/./attached_files/070 Modeling Other Items Interest expenses Extraordinary items and Taxes/9.Interest-expenses-Extraordinary-items-and-Taxes-Solved.xlsm.tmp, cause: The system cannot find the path specified.

10/20 11:55:31 [NOTICE] Download GID#3443330499470c24 not complete: C:/Users/Richard/Documents/udemy-dl-windows/the-complete-investment-banking-course-2016/13 DCF Valuation - Forecasting of key PL items/./attached_files/070 Modeling Other Items Interest expenses Extraordinary items and Taxes/9.Interest-expenses-Extraordinary-items-and-Taxes-Solved.xlsm.tmp

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
344333|ERR |       0B/s|C:/Users/Richard/Documents/udemy-dl-windows/the-complete-investment-banking-course-2016/13 DCF Valuation - Forecasting of key PL items/./attached_files/070 Modeling Other Items Interest expenses Extraordinary items and Taxes/9.Interest-expenses-Extraordinary-items-and-Taxes-Solved.xlsm.tmp

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
 Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 825, in udemy_dl
  File "udemy_dl.py", line 718, in get_data
  File "udemy_dl.py", line 612, in get_attached_file
  File "udemy_dl.py", line 675, in check_downloaded
WindowsError: [Error 3] The system cannot find the path specified
Failed to execute script udemy_dl

**Comment by darknightCoder** [comment]
running update.cmd from the folder solved it for me....

**Comment by Leovalcante** [comment]
@darknightCoder i tried to follow your advice but it didn't work for me.

@richard2092  your error was already reported in issue #146 and earlier in issue #116 : WindowsError: [Error 3] The system cannot find the path specified.


This is an explanation of @poode:
> I faced that error too because the course attachment sometimes not a file. It is a url for a another website


This is the way i solved:
> I solved using the option --lecture-start NUMBER_OF_NEXT_LESSION.
I've checked the data after the full download and the data are all ok.

Hope this helps 😸

Have a nice day,
Valerio

**Comment by Homless** [comment]
Trying to log in ...
 Login success.
 Found course id: logo-coral.svg
I have this problem... 

Exception
Traceback (most recent call last):
  File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 772, in udemy_dl
  File "udemy_dl.py", line 227, in get_course_title
KeyError: u'title'
Failed to execute script udemy_dl
