### ISSUE TITLE
Getting the attached error

### ISSUE THREAD

**Issue by shankargv** [nishad/udemy-dl-windows#27]
I am getting the attached error when downloading a premium course I have enrolled in. I tried it with a different premium course I have and it worked, it just gives me this error for only one course. Could you let me know the reason for this? Thanks, btw this tool is awesome and really appreciate you sharing this. 

Traceback (most recent call last):
  File "<string>", line 288, in <module>
  File "<string>", line 284, in main
  File "<string>", line 208, in udemy_dl
  File "<string>", line 102, in login
  File "<string>", line 96, in get_csrf_token
  File "<string>", line 86, in get
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\requests.sessions", line 477,
in get
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\requests.sessions", line 465,
in request
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\requests.sessions", line 573,
in send
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\requests.adapters", line 424,
in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.udemy.com', port=443): Max retries exceeded with url: /join/login-popup (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Authentication Required',)))

**Comment by shankargv** [comment]
Sorry, found the issue, it was due to a proxy at my end. It is working now after I disabled the proxy.
