### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by surajy** [nishad/udemy-dl-windows#52]
```
Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\udemy ripper\udemy-dl.py", line 185, in <module>
    main()
  File "C:\Users\ADMIN\Desktop\udemy ripper\udemy-dl.py", line 180, in main
    login = register()
  File "C:\Users\ADMIN\Desktop\udemy ripper\udemy-dl.py", line 57, in register
    csrf_grabber = httper.open('https://www.udemy.com/join/signup-submit/')
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND
>>> 
```

**Comment by nishad** [comment]
This error, code or implementation doesn't have any relation to this project. This isn't a general discussion forum. This is an issue tracker for the project `udemy-dl-win`
