### ISSUE TITLE
Traceback error how to fix it ??

### ISSUE THREAD

**Issue by farazhussain2015** [nishad/udemy-dl-windows#53]
how to fix it 
Traceback (most recent call last):
  File "<string>", line 374, in <module>
  File "<string>", line 370, in main
  File "<string>", line 290, in udemy_dl
  File "<string>", line 232, in get_video_links
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 3: ordinal not in range(128)

**Comment by sangeeth5320** [comment]
How to fix it 

INFO-884] Downloading to: F:\udemy-dl-win-2.1.2\udemy-dl-win\the-complete-developers-guide-to-mongodb

INFO-127] Trying to log in ...
ERROR-1198] Traceback (most recent call last):
 File "<string>", line 889, in <module>
 File "<string>", line 886, in main
 File "<string>", line 697, in udemy_dl
 File "<string>", line 129, in login
 File "<string>", line 115, in get_csrf_token
 File "<string>", line 85, in get
 File "site-packages\requests\sessions.py", line 480, in get
 File "site-packages\requests\sessions.py", line 468, in request
 File "site-packages\requests\sessions.py", line 576, in send
 File "site-packages\requests\adapters.py", line 447, in send
SLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
one

**Comment by AkashShivanand** [comment]
You can use `--safe-file-names` to download without any _error_...
