### ISSUE TITLE
[BUG] ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by lordganja** [nishad/udemy-dl-windows#58]
```
Traceback (most recent call last):
  File "<string>", line 374, in <module>
  File "<string>", line 370, in main
  File "<string>", line 290, in udemy_dl
  File "<string>", line 207, in get_video_links
  File "C:\dev\udemy-dl-windows\build\udemy-dl\out00-PYZ.pyz\requests.models", line 819, in json
  File "C:\dev\udemy-dl-windows\build\udemy-dl\out00-PYZ.pyz\json", line 338, in loads
  File "C:\dev\udemy-dl-windows\build\udemy-dl\out00-PYZ.pyz\json.decoder", line 366, in decode
  File "C:\dev\udemy-dl-windows\build\udemy-dl\out00-PYZ.pyz\json.decoder", line 384, in raw_decode
ValueError: No JSON object could be decoded
```

**Comment by moreirawebmaster** [comment]
I have this same problem when trying to download a preview course it returns this message, so I noticed the URL has changed now, with some parameters to more like:

https://www.udemy.com/connection/learn/?dtcode=pfZBBQa4D0Nl#/

**Comment by nishad** [comment]
Fixed with https://github.com/nishad/udemy-dl-windows/releases/tag/v2.1.1.
