### ISSUE TITLE
Problem downloading w/ non-English characters

### ISSUE THREAD

**Issue by bcooney** [nishad/udemy-dl-windows#9]
Downloading the video content for a Chinese class. When the downloader meets Chinese characters, it is unable to proceed. The downloader incorrectly interprets the Chinese 人 as Σ║║  -- see below for full error:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
5417e2|OK  |    22KiB/s|C:/Users/brendan.cooney/Downloads/udemy-dl-win-1.8.0/ude
my-dl-win/dc-level-1/01 Lesson 5 - Growing up/002 An introduction to beautiful t
hings.mp4

Status Legend:
(OK):download completed.

Downloading 003 A grown-up Σ║║.mp4
Traceback (most recent call last):
  File "<string>", line 288, in <module>
  File "<string>", line 284, in main
  File "<string>", line 225, in udemy_dl
  File "<string>", line 201, in get_video
  File "<string>", line 29, in download
  File "<string>", line 53, in aria2c_dl
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\subprocess
", line 522, in call
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\subprocess
", line 710, in __init__
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\subprocess
", line 958, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character u'\u4eba' in position 6
43: ordinal not in range(128)

**Comment by nishad** [comment]
Please use this solution, provided here for the timebeing.

https://github.com/nishad/udemy-dl-windows/issues/5#issuecomment- 137988471

:sake

**Comment by bcooney** [comment]
Still grabs the title incorrectly (same as above), but does download the file. Thanks for the quick support!

**Comment by nishad** [comment]
Only in the terminal display, it will be wrong, but the file names downloaded will be correct.
